---
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=600"]
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable
      - id: file-contents-sorter
        files: requirements.txt|\.gitignore|\.dockerignore

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(alloy|yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict -f parsable

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        # files: (?:^|/)([Dd]ockerfile|[Dd]ockerfile\..*)$
        entry: hadolint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      # - id: bundler-audit
      # - id: check-mailmap
      # - id: fasterer
      # - id: forbid-binary
      # - id: forbid-space-in-indent
      # - id: git-check  # Configure in .gitattributes
      # - id: git-dirty  # Configure in .gitignore
      # - id: markdownlint # Configure in .mdlrc
      # - id: reek
      # - id: require-ascii
      # - id: rubocop
      # - id: script-must-have-extension
      # - id: script-must-not-have-extension
      - id: shellcheck
      - id: shfmt
ci:
  autoupdate_schedule: weekly
